---
- name: "install essential packages"
  package:
    name:
      - "gdb"
      - "python3-dev"
      - "libssl-dev"
      - "libffi-dev"
      - "build-essential"
      - "powershell"
      - "gobuster"
      - "neo4j"
      - "bloodhound"
      - "ruby"
      - "gcc-mingw-w64-x86-64"
      - "g++-mingw-w64-x86-64"
      - "wine64"
      - "apt-transport-https"
  become: yes

- name: "create tools directory"
  file:
    path: ~/tools
    state: directory

- name: Install kiss
  git:
    repo: https://github.com/MrJizzler/kiss.git
    dest: ~/tools/kiss

- name: Install impacket
  block:
  - name: Clone impacket
    git:
      repo: https://github.com/SecureAuthCorp/impacket.git
      dest: ~/tools/impacket

  - name: Install impacket
    shell:
      cmd: pip3 install .
      chdir: ~/tools/impacket

- name: Install john
  git:
    repo: https://github.com/magnumripper/JohnTheRipper.git
    dest: ~/tools/JohnTheRipper

- name: Install nishang
  git:
    repo: https://github.com/samratashok/nishang.git
    dest: ~/tools/nishang

- name: Install SecLists
  git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: ~/tools/SecLists

- name: Install peda
  block:
  - name: Clone peda
    git:
      repo: https://github.com/longld/peda.git
      dest: ~/tools/peda
  - name: Install peda
    shell: echo "source $HOME/tools/peda/peda.py" >> $HOME/.gdbinit

- name: Install pwntools
  shell: python3 -m pip install --upgrade pip && python3 -m pip install --upgrade pwntools

- name: Install AutoRecon
  block:
  - name: Clone AutoRecon
    git:
      repo: https://github.com/Tib3rius/AutoRecon.git
      dest: ~/tools/AutoRecon
  - name: Install AutoRecon
    shell: pip3 install -r $HOME/tools/AutoRecon/requirements.txt

- name: Install kerbrute
  block:
  - name: Clone kerbrute
    git:
      repo: https://github.com/TarlogicSecurity/kerbrute.git
      dest: ~/tools/kerbrute
  - name: Install kerbrute
    shell: pip3 install -r $HOME/tools/kerbrute/requirements.txt

- name: Install privilege-escalation-awesome-scripts-suite
  git:
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
    dest: ~/tools/privilege-escalation-awesome-scripts-suite

- name: Install autochrome
  block:
  - name: Clone autochrome
    git:
      repo: https://github.com/nccgroup/autochrome.git
      dest: ~/tools/autochrome
  - name: Install autochrome
    shell: ruby $HOME/tools/autochrome/autochrome.rb
    ignore_errors: yes

- name: Install Windows Sysinternals
  block:
    - name: Create sysinternals directory
      file:
        path: ~/tools/sysinternals
        state: directory
    - name: Download Windows Sysinternals
      shell:
        cmd: wget https://live.sysinternals.com/files/SysinternalsSuite.zip && unzip SysinternalsSuite.zip && rm SysinternalsSuite.zip
        chdir: ~/tools/sysinternals

- name: Install ysoserial
  block:
    - name: Create ysoserial directory
      file:
        path: ~/tools/ysoserial
        state: directory
    - name: Download ysoserial.jar
      shell:
        cmd: wget https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar
        chdir: ~/tools/ysoserial

- name: Install ysoserial.net
  git:
    repo: https://github.com/pwntester/ysoserial.net.git
    dest: ~/tools/ysoserial.net

- name: Install pypykatz
  pip:
    name: pypykatz
