---
- name: "install tmux"
  package:
    name:
      - "tmux"
  become: true

- name: "copy tmux config"
  copy:
    src: ".tmux.conf"
    dest: "~/.tmux.conf"

- name: "install tmux logging"
  git:
    repo: "https://github.com/tmux-plugins/tmux-logging.git"
    dest: "~/tmux-logging"


